language: elixir
elixir:
  - 1.2.5
otp_release:
  - 18.2.1
env:
  - DB=postgresql
script:
  - mix test
before_install:
  - mix local.hex --force
  - mix deps.get
before_script:
  - psql -c 'create database pxblog_dev' -U postgres
